import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background text-foreground overflow-x-hidden w-screen relative`}
      >
        <Header />
        <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start min-h-screen">
          {children}
        </main>
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
          Something in the footer
        </footer>
      </body>
    </html>
  );
}
